use_frameworks!

platform :ios, '10.0'

target 'DEACBilayerTabBarViewController_Example' do
  pod 'DEACBilayerTabBarViewController', :path => '../'

  target 'DEACBilayerTabBarViewController_Tests' do
    inherit! :search_paths

    
  end
end
