use_frameworks!

platform :ios, '10.0'

target 'DEACBilayerTabBarViewController_Example' do
  pod 'DEACBilayerTabBarViewController', :path => '../'
  
  pod 'LookinServer', :configurations => ['Debug']

  target 'DEACBilayerTabBarViewController_Tests' do
    inherit! :search_paths

    
  end
end
